spring:
  datasource:
    url: jdbc:postgresql://oneplast-db.internal:5432/surl_prod
    #    url: jdbc:postgresql://localhost:5434/surl_prod
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false

  jpa:
    properties:
      format_sql: false
      highlight_sql: false
      use_sql_comments: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    io.river.flyiopostgres: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
